config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'projects#index'
  
  resources :projects, :messages
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord

  validates :name, :email, :description, presence: true
  validates :name, :email, length: { minimum: 2 }
  validates :name, length: { maximum: 25 }
  validates :description, length: { minimum: 25 }
  validates :description, length: { maximum: 300 }
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      MessageMailer.with(message: @message).confirmation_email.deliver_later
      flash[:success] = "Your message has successfully been sent! 
      You should receive an email confirmation soon."
    else
      flash.now[:error] = "Please fix the errors."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "navbar" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'projects/navbar' %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/261517eee2.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/create.html.erb
<%= turbo_frame_tag "response" do %>
  <p class="text-center fs-4">The form was submitted successfully.</p>
<% end %>

app/views/messages/index.html.erb
<div class="container vh-100">
  <div class="col pt-5">
    <div class="pt-5">
      <% @messages.each do |message| %>
        <div class="container p-3">
          <%= link_to message_path(message), class: "text-decoration-none" do %>
            <div class="text-dark">
              <div class="py-3 border border-dark shadow bg-light rounded">
                <div class="p-2">
                  <div class="m-2">
                    <p class=""><span class="fw-bold">Name:</span> <%= message.name %> </p>
                  </div>

                  <div class="m-2">
                    <p class=""><span class="fw-bold">Email:</span> <%= message.email %> </p>
                  </div>

                  <div class="text-center pt-3">
                    <p class="fw-bold">Message:</p>
                  </div>
                  <div class="">
                    <%= message.description %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="container min-vh-100 py-5" id="contact">
  <div class="col">
    <div class="col">
      <div class="p-5">
        <div class="text-center">
          <div class="row">
            <p class="h1">Contact</p>
          </div>
          <div class="line"></div>
          <div class="row">
            <p class="fs-4 mt-4">Contact me via the form below and 
            I will respond as soon as possible.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="col container" id="form">
      <div class="form-padding">
        <div class="bg-light rounded">
          <div class="shadow p-3 mb-5 rounded">

            <%= turbo_frame_tag "response" do %>

              <div class="">
                <%= form_with model: @message, class: "needs-validation" do |form| %>
                  <div class="p-3">
                    <%= form.label "Name:" %>
                    <%= form.text_field :name, class: "form-control p-3", required: true %>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                  </div>

                  <div class="p-3">
                    <%= form.label "Email:" %>
                    <%= form.email_field :email, class: "form-control p-3", required: true  %>
                  </div>

                  <div class="p-3">
                    <%= form.label "Message:" %>
                    <%= form.text_area :description, class: "form-control p-3", rows: "6", required: true %>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                  </div>

                  <div class="mt-3 d-flex justify-content-end">
                    <%= form.submit "Submit", class: "btn btn-success px-5 py-2" %>
                  </div>

                  <% if @message.errors.any? %>
                    <div class="p-5">
                      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this article from being saved:</h2>

                      <ul>
                        <% @message.errors.each do |error| %>
                          <li class="pt-2 text-danger"><%= error.full_message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>


                <% end %>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/messages/show.html.erb
<div class="vh-100 d-flex justify-content-center align-items-center">
  <div class="container">
    <div class="py-3 border border-dark shadow bg-light rounded">
      <div class="p-2">
        <div class="m-2">
          <p class=""><span class="fw-bold">Name:</span> <%= @message.name %> </p>
        </div>

        <div class="m-2">
          <p class=""><span class="fw-bold">Email:</span> <%= @message.email %> </p>
        </div>

        <div class="text-center pt-3">
          <p class="fw-bold">Message:</p>
        </div>
        <div class="">
          <%= @message.description %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_about.html.erb
<div class="container min-vh-100 py-5" id="about">
  <div class="col">

    <div class="row">
      <div class="text-center justify-content-center">
        <div class="p-5">
          <p class="h1">About Me</p>
          <div>
            <div class="line"></div>
          </div>
          <p class="fs-4 mt-4"> Here you can find more about me. My education, qualifications, 
          work expereince and skills.</p>
        </div>
      </div>
    </div>

    <div class="main">
      <div class="about">
        <div class="col me-3">
          <div class="row">
            <p class="h2 fw-bold">Get to know me!</p>
          </div>
          <div class="row">
            <p class="mt-3">I'm a <b>Software Developer</b> focused on building 
            the Frontend and Backend of Websites and Web Applications. 
            Checkout out my work in the <b>Projects</b> section.</p>
            <br>
            <p class="">
            Feel free to connect or follow me on 
            <%= link_to 'Linkedin', 'https://www.linkedin.com/in/liam-hayden-770877207/', target: 'blank' %> 
            and <%= link_to 'Github', 'https://github.com/LiamHayden', target: 'blank' %>.
            </p>
            <br>
            <p class="">
            I have received both a QQI Level 6 <b>Advanced Certificate in 
            Software Development</b> and a QQI Level 5 in <b>Computer Science</b>, 
            both with distinction. Along with completing a <b>Ruby on Rails 
            internship</b>, with Athena Analytics. 
            From there, I have continued to develop my skill set by creating 
            several projects and am currently studying for my <b>CompTIA Network +</b> exam.
            </p>
            <br>
            <p class="">
            I am currently open to jobs that will allow me to develop my skill set 
            further while helping me to gain new skills and experiences. 
            If you are interested in reaching out or have an inquiry, 
            please feel free to <b>contact</b> me.
            </p>
          </div>
          <div class="mt-3">
            <%= link_to 'Contact', '/messages/new', class:"btn btn-success px-5 py-2" %>
          </div>
        </div>
        <div class="col ms-3">
          <div class="row">
            <p class="h2 fw-bold">My skills</p>
          </div>
          <div class="m-3 d-flex flex-wrap">
            <p class="tile">Ruby</p>
            <p class="tile">Java</p>
            <p class="tile">Ruby on Rails</p>
            <p class="tile">SQL</p>
            <p class="tile">Agile Development</p>
            <p class="tile">HTML</p>
            <p class="tile">CSS</p>
            <p class="tile">Bootstrap</p>
            <p class="tile">GIT</p>
            <p class="tile">Github</p>
            <p class="tile">Linux</p>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/projects/_contact.html.erb
<div class="container min-vh-100 d-flex justify-content-center align-items-center" id="contact">
  <div class="">
    <div class="col">
      <div class="col">
        <div class="p-5">
          <div class="text-center">
            <div class="row">
              <p class="h1">Contact</p>
            </div>
            <div class="line"></div>
            <div class="row">
              <p class="fs-4 mt-4">Contact me via the button below and 
              I will respond to you ASAP.</p>
            </div>
            <div class="mt-3">
              <%= link_to 'Contact', '/messages/new', class:"btn btn-success px-5 py-2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_footer.html.erb
<div class="max-vh-25 py-5 bg-dark ">
  <div class="col">
    <div class="text-center justify-content-center">
      <p class="text-light">Created by 
        <%= link_to 'Liam Hayden', '#', target: 'blank' %>.</p>
    </div>
  </div>
</div>

app/views/projects/_home.html.erb
<div class="bg-grad">
  <div class="container">
    <div class="icon-bar">
      <div class="position-absolute top-50 start-0">
        <div class="border rounded-end">
          <div class="bg-white shadow">
            <div class="row icon-outside", data-bs-toggle="tooltip" title="Github">
              <div class="p-4">
                <%= link_to '<i class="fa-brands fa-github icon"></i>'.html_safe, 'https://github.com/LiamHayden', target: 'blank', class: "icon" %>
              </div>
            </div>
            <div class="row icon-outside", data-bs-toggle="tooltip" title="Gmail">
              <div class="p-4">
                <%= mail_to 'liam.hayden.code@gmail.com', '<i class="fa-solid fa-envelope icon"></i>'.html_safe, class: "icon" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="vh-100 d-flex justify-content-center align-items-center", id="home">
      <div class="mx-5">
        <div class="text-center">
          <div class="row">
            <div class="">
              <p class="h1 fw-bold">Hey, I'm Liam Hayden</p>
            </div>
          </div>
          <div class="row">
            <div class="mt-3">
              <p class="fs-4">A Software Developer focused on building the Frontend and Backend of Websites
               and Web Applications. </p>
            </div>
          </div>
          <div class="row">
            <div class="mt-3">
              <%= link_to "Projects", "#projects", class: "btn btn-success px-5 py-2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_navbar.html.erb
<%# hidden dropdown element %>
<div class="fixed-top" data-controller="toggle" >
  <%# mobile navbar %>
  <nav class="navbar fixed-top navbar-dark bg-dark" id="hamburger">
    <div class="container-fluid">
    <a class="navbar-" href="/#home"> 
      <%= image_tag "logo.png", alt: "Liam Hayden site logo", style: "width:70px" %> 
    </a>
      <button class="navbar-toggler" type="button" data-action="click->toggle#menu">
        <i class="fa-solid fa-bars fs-2 m-2" data-toggle-target="hamburger"></i>
        <i id="hidden" class="fa-solid fa-x fs-2 m-2" data-toggle-target="close"></i>
      </button>
    </div>
  </nav>
  <div id="hidden" data-toggle-target="menu">
    <div class="navbar-dark bg-dark pt-5">
      <div class="shadow-3 p-4">
        <div class="nav flex-column align-items-center">
          <div class="">
            <li class="nav-item py-3">
              <%= link_to "Home", "/#home", class: "text-decoration-none li" %>
            </li>
            <li class="nav-item py-3">
              <%= link_to "About", "/#about", class: "text-decoration-none li" %>
            </li>
            <li class="nav-item py-3">
              <%= link_to "Projects", "/#projects", class: "text-decoration-none li" %>
            </li>
            <li class="nav-item py-3">
              <%= link_to "Contact", "/#contact", class: "text-decoration-none li" %>
            </li>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# desktop navbar %>
<nav class="navbar fixed-top navbar-dark bg-dark" id="nav-bar">
  <div class="container-fluid">
    <a class="navbar-" href="/#home"> 
      <%= image_tag "logo.png", alt: "Liam Hayden site logo", style: "width:70px" %> 
    </a>
    <ul class="nav col-sm justify-content-end">
      <li class="nav-item">
        <%= link_to "Home", "/#home", class: "text-decoration-none px-2 li" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", "/#about", class: "text-decoration-none px-2 li" %>
      </li>
      <li>
        <%= link_to "Projects", "/#projects", class: "text-decoration-none px-2 li" %>
      </li>
      <li>
        <%= link_to "Contact", "/#contact", class: "text-decoration-none px-2 li" %>
      </li>
    </ul>
  </div>
</nav>

app/views/projects/_projects.html.erb
<div class="bg-grad" id="projects">
  <div class="container min-vh-100 py-5" id="about">
    <div class="col">

      <div class="row">
        <div class="text-center justify-content-center">
          <div class="p-5">
            <p class="h1">Projects</p>
            <div>
              <div class="line"></div>
            </div>
            <p class="fs-4 mt-4">Here you can find my <b>current</b> and <b>previous</b> <b>Ruby on Rails</b>
            projects.</p>
          </div>
        </div>
      </div>
      <% if @projects.present? %>
        <% @projects.each do |project| %>
          <div class="main">
            <div class="about">
              <div class="col me-3">
                <div class="row g-0">
                  <%= image_tag project.img, alt: "Image of project", 
                  class: "shadow-lg rounded" %>
                </div>
              </div>
              <div class="col ms-3">
                <div class="row">
                  <p class="h2 fw-bold"> <%= project.title %> </p>
                </div>
                <div class="">
                  <p class="mt-3"> <%= project.description %> </p>
                </div>
                <div class="">
                  <%= link_to "Link", project.link, target: 'blank', class: "btn btn-success px-5 py-2" %>
                </div>
              </div>
            </div>
          </div>
          <div style="padding-bottom:10rem;"></div>
        <% end %>
      <% else %>
        <div class="text-center">
          <p class="fs-1">Projects coming soon...</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'home' %>
<%= render 'about' %>
<%= render 'projects' %>
<%= render 'contact' %>
<%= render 'footer' %>